# Generated by Django 2.0.9 on 2018-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('res', models.TextField()),
                ('emaill', models.EmailField(max_length=254)),
            ],
        ),
    ]
