# Generated by Django 2.0.9 on 2018-12-07 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdate',
            field=models.TextField(default=datetime.datetime(2018, 12, 7, 11, 3, 47, 417417, tzinfo=utc)),
        ),
    ]
